# secrets.py (hardcoded placeholders)
# Replace these with your actual API credentials

HUNTRESS_KEY = "YOUR_HUNTRESS_KEY"
HUNTRESS_SECRET = "YOUR_HUNTRESS_SECRET"

AXCIENT_API_KEY = "YOUR_AXCIENT_API_KEY"

NINJA_CLIENT_ID = "YOUR_NINJA_CLIENT_ID"
NINJA_CLIENT_SECRET = "YOUR_NINJA_CLIENT_SECRET"
